services:

  nginx:
    image: nginx:latest
    container_name: nginx_cdn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/etc/nginx/mime.types:ro
      - ./content:/usr/share/nginx/cdn:ro
    networks:
      - masternetwork

  
  kriya25masterbackend:
    image: ghcr.io/akashshanmugraj/kriyabackend:latest
    container_name: kriya25masterbackend
    ports:
      - "6000:4300"
    environment:
      - META_ACCESS_TOKEN=${META_ACCESS_TOKEN}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - RECIPIENT_WAID=${RECIPIENT_WAID}
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
      - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTSECRET}
      - MONGO_URI=${MONGO_URI}
    networks:
      - masternetwork
  
  kriya25masterfrontend:
    image: ghcr.io/akashshanmugraj/kriyafrontend:latest
    container_name: kriya25masterfrontend
    ports:
      - "6001:3000"
  
  kriya25helpdesk:
    image: ghcr.io/akashshanmugraj/kriyahelpdesk:latest
    container_name: kriya25helpdesk
    ports:
      - "6002:3000"
    environment:
      - USERNAME=${HELPDESKUSERNAME}
      - PASSWORD=${HELPDESKPASSWORD}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - masternetwork
  
  kriya25hostel:
    image: ghcr.io/akashshanmugraj/kriyahostel:latest
    container_name: kriya25hostel
    ports:
      - "6003:3000"
    environment:
      - USERNAME=${HOSTELUSERNAME}
      - PASSWORD=${HOSTELPASSWORD}
      - BACKEND_URL=${HOSTELBACKEND_URL}
    networks:
      - masternetwork
  
  kriya25admin:
    image: ghcr.io/kishoreadhith-v/kriya-admin-frontend:latest
    container_name: kriya25admin
    ports:
      - "6004:3000"
    environment:
      - USERNAME=${ADMINUSERNAME}
      - PASSWORD=${ADMINPASSWORD}
      - BACKEND_URL=${BACKEND_URL}
  
  kriya25convenerfrontend:
    image: ghcr.io/akashshanmugraj/kriyaconvener:latest # TODO: replace with valid URL
    container_name: kriya25convenerfrontend
    ports:
      - "6005:3000"
    environment:
      - USERNAME=${CONVENERUSERNAME}
      - PASSWORD=${CONVENERPASSWORD}
      - BACKEND_URL=${BACKEND_URL}
  
  kriya25convenerbackend:
    image: ghcr.io/akashshanmugraj/kriya-convenor-backend:latest
    container_name: kriya25convenerbackend
    ports:
      - "6006:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
  
  kriya25messenger: # TODO: yet to create application
    image: ghcr.io/akashshanmugraj/kriyamessenger:latest
    container_name: kriya25messenger
    ports:
      - "6007:8080"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - BACKEND_URL=${BACKEND_URL}

  kriya25payment1:
    image: ghcr.io/akashshanmugraj/kriyapayment1:latest
    container_name: kriya25payment1
    environment:
      - MONGOURI=${MONGOURI}
    ports:
      - "6010:6010"
    networks:
      - masternetwork

  kriya25payment2:
    image: ghcr.io/akashshanmugraj/kriyapayment2:latest
    container_name: kriya25payment2
    environment:
      - MONGOURI=${MONGOURI}
    ports:
      - "6011:6011"
    networks:
      - masternetwork

  nginxmongo:
    image: mongo
    ports:
      - "27030:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo_data:/data/db
    networks:
      - masternetwork
      
networks:
  cdn_network:
    driver: bridge