services:

  nginx:
    image: nginx:latest
    container_name: nginx_grd_proxy
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro